name: Add to wiki
description: Submit your own articles to be added to our wiki and help others.
labels: ["Status: Pending", "Type: Add"]
body:
  - type: markdown
    attributes:
      value: |
        *Thank you for choosing to contribute to our community.*
        
        ---
        
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: "Please make sure you have checked all of the following:"
      options:
        - label: I have verified that no one has published an article similar to this one.
          required: true
  - type: markdown
    attributes:
      value: |
        --- 
        
        # What do you want to share with us today?
  - type: input
    id: name
    attributes:
      label: Author name
      description: This will appear in your post, what is the name of the person who wrote it?
      placeholder: 
    validations:
      required: true
  - type: input
    id: profile
    attributes:
      label: Author profile link
      description: You can share the author profile link on GitHub or Telegram to be added to your article credits.
      placeholder: https://
    validations:
      required: true
  - type: textarea
    id: photo
    attributes:
      label: Author profile picture
      description: You can upload a custom photo to appear next to the author name in this publication. 
      placeholder: 
    validations:
      required: true
    ---
  - type: markdown
    id: text
    attributes: # Title
      label: Write your article
      description: Write your article using markdown formatting, and remember to write only in English, any other language will be manually translated by a moderator before the article goes on the wiki.
    validations:
      required: true
